acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('chpass/', views.chpass, name="chpass")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views
app_name = "vote"
urlpatterns = [
    path('index/' , views.index, name="index"),
    path('detail/<tpk>', views.detail, name="detail"),
    path('vote/<tpk>', views.vote, name='vote'),
    path('cancel/<tpk>', views.cancel, name='cancel'),
    path('create/', views.create, name="create")
]

vote/models.py
from django.db import models
from acc.models import User
# Create your models here.
class Topic(models.Model):
    subject = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")

    def __str__(self):
        return self.subject

class Choice(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    comment = models.TextField()
    choicer = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f"{self.topic}_{self.name}"

vote/views.py
from django.shortcuts import render, redirect
from .models import Topic, Choice
# Create your views here.
def index(request):
    t = Topic.objects.all()
    context = {
        "tset" : t
    }
    return render(request, "vote/index.html", context )


def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        t = Topic(subject=s, maker=request.user, content=c)
        t.save()
        cn = request.POST.getlist("cname")
        cc = request.POST.getlist("ccom")
        for name, com in zip(cn,cc):
            Choice(topic=t, name=name, comment=com).save()
        return redirect("vote:index")

    return render(request, "vote/create.html")

def cancel(request, tpk):
    u = request.user
    t = Topic.objects.get(id=tpk)
    t.voter.remove(u)
    u.choice_set.get(topic=t).choicer.remove(u)
    return redirect("vote:detail", tpk)


def vote(request, tpk):
    t = Topic.objects.get(id=tpk)
    if not request.user in t.voter.all():
        t.voter.add(request.user)
        cpk = request.POST.get("cho")
        c = Choice.objects.get(id=cpk)
        c.choicer.add(request.user)
    return redirect("vote:detail", tpk)

def detail(request, tpk):
    t = Topic.objects.get(id=tpk)
    c = t.choice_set.all()
    context = {
        "cset" : c,
        "t" : t
    }
    return render(request, "vote/detail.html" , context)

templates/vote/create.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>토픽생성</b></h1>
    <div class="mt-4">
        <form method="post">
            {% csrf_token %}
            <input type="text" class="form-control" name="sub" placeholder="INPUT SUBJECT">
            <textarea class="form-control mt-4" name="con" placeholder="INPUT CONTENT" style="height: 150px;"></textarea>

            <div class="text-center mt-4">
                <button type="button" class="btn btn-dark" onclick="makecho()" style="width: 40%;">보기생성</button>
                <button class="btn btn-primary" style="width: 40%;">토픽생성</button>
            </div>

            <div class="row mt-5" id="here">
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="cname" placeholder="INPUT BOGI NAME">
                    <textarea class="form-control mt-4" name="ccom" placeholder="INPUT COMMENT" style="height: 100px;"></textarea>
                </div>
            </div>
        </form>
    </div>

    <script>
        function makecho(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.setAttribute("class","col-sm-4");
            n.innerHTML = '<input type="text" class="form-control" name="cname" placeholder="INPUT BOGI NAME">\
                <textarea class="form-control mt-4" name="ccom" placeholder="INPUT COMMENT" style="height: 100px;"></textarea>';
            d.appendChild(n);
        }
    </script>


{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}
{% block con %}
    {% load mathfilters %}
    <h1><b>{{ t.subject }}</b></h1>

    <div class="row mt-4">
        <div class="col-sm-8">
            <textarea class="form-control" disabled style="height: 200px;">{{ t.content }}</textarea>
        </div>
        <div class="col-sm-4">
            <img src="{{ t.maker.getpic }}" width="100%">
            <div class="text-center mt-3"><b>{{ t.maker }}</b></div>
        </div>
    </div>

    {% if user in t.voter.all %}
    

            <div class="row mt-4">
                {% for i in cset %}
                    <div class="col-sm-4">
                        <b>{{i.name}}</b>
                        <sup>{{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }} %</sup>
                        <div class="progress mt-3">
                            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: {{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }}%"></div>
                        </div>
                        <textarea class="form-control mt-3" style="height: 100px;" disabled>{{ i.comment }}</textarea>
                    </div>
                {% endfor %}
            </div>

            <div class="mt-4 text-end">
                <a class="btn btn-danger" href="{% url 'vote:cancel' t.id %}">무르기</a>
            </div>
 
    {% else %}
        <form method="post" action="{% url 'vote:vote' t.id %}">
            {% csrf_token %}
            <div class="row mt-4">
                {% for i in cset %}
                    <div class="col-sm-4">
                        <input type="radio" name="cho" value="{{ i.id }}" {% if forloop.first %}checked{% endif %}> <b>{{i.name}}</b>
                        <textarea class="form-control mt-3" style="height: 100px;" disabled>{{ i.comment }}</textarea>
                    </div>
                {% endfor %}
            </div>

            <div class="mt-4 text-end">
                <button class="btn btn-dark">투표</button>
            </div>
        </form>
    {% endif %}
{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>투표소</b></h1>

    <div class="text-end">
        <a href="{% url 'vote:create' %}" class="btn btn-dark">토픽생성</a>
    </div>

    <ul>
    {% for i in tset %}
        <li><a href="{% url 'vote:detail' i.id %}">{{ i.subject }}</a></li>
    {% endfor %}
    </ul>

{% endblock %}